### ISSUE TITLE
warning: adding 'int' to a string does not append to the string

### ISSUE THREAD

**Issue by ryandesign** [micans/zoem#2]
On my macOS 10.15.7 system the clang compiler showed this warning when compiling zoem 21-341:
```
ops.c:853:60: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
      ;  mcxTingNAppend(data, "_abcdefghijklmnopqrstuvwxyz"+r, 1)
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
ops.c:853:60: note: use array indexing to silence this warning
      ;  mcxTingNAppend(data, "_abcdefghijklmnopqrstuvwxyz"+r, 1)
                                                           ^
                              &                            [ ]
1 warning generated.
```

**Comment by micans** [comment]
This is valid code, `+r` points to a string inside. Array indexing is a road to nowhere here  as I need a string, not a `char`. (looking at the routine `text_map_alpha` I do question my sanity and how pointless it all is, but that is a different issue). So ... I've made a note [in the source that Clang does not like this (bundled with a script upload)](https://github.com/micans/zoem/commit/f3e2c9cef590ba384088a0ce610f798d8d6b671c), but don't see what I can do that's not a contortion. I'm closing this for now but happy to take advice on how to appease clang in a dignied manner.

**Comment by ryandesign** [comment]
Yes I see...

Does the patch at the bottom of this email show a method that might work?

https://patchwork.kernel.org/project/dash/patch/20181215174932.11635-2-ao2@ao2.it/

**Comment by micans** [comment]
Thanks - genuinely interesting this sort of thing. In that case there is already a variable, and the pointer arithmetic is split into two parts. It seems weird that Clang  no longer complains, as the same thing happens, but I sort of see the point. Is it the case that Clang warnings need to be fixed in order for code to be allowed through? That will certainly motivate me (although this fix will be pretty contortionist in this (zoem) setting).

**Comment by ryandesign** [comment]
> Is it the case that Clang warnings need to be fixed in order for code to be allowed through?

Not at all, I just wanted to let you know about it since I'm not as experienced with C and wasn't sure if this might represent a coding error. In other instances, Clang's new warnings have been very helpful in pointing out obviously wrong code that went unnoticed for a long time, though that doesn't seem to be the case here.

**Comment by micans** [comment]
Closing this again as I'll leave it for now. A marker `clangface` has been added to the source to remind of it.
