### ISSUE TITLE
Program segfaults under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [micans/zoem#5]
zoem -h does not, but zoem  without parameters segfaults.
```
(gdb) file /usr/bin/zoem
Reading symbols from /usr/bin/zoem...
(No debugging symbols found in /usr/bin/zoem)
(gdb) run
Starting program: /usr/bin/zoem
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7d0cbca in ?? () from /usr/lib/libc.so.6
```

**Comment by micans** [comment]
That is unfortunate. This is from an Arch package of zoem I assume. Which version is this? Without more information (e.g. backtrace from a zoem with debugging symbols) I don't know what I can do (this particular use I've tested on quite a few different systems). If you tell me the version (zoem --version) I can have a look at that particular version. Presumably it's 11.166-2. Although it is quite old, it has been the stable zoem release until very recently.

**Comment by stefanhusmann** [comment]
It is both in 11.166-2 (reported by other som time ago) and in the newest tarball version 21.341. 
```
$ zoem --version
zoem (null)
(c) Copyright 2001 Stijn van Dongen.
(c) Copyright 2021 Stijn van Dongen.
zoem comes with NO WARRANTY to the extent permitted by law.
You may redistribute copies of zoem under the terms
of the GNU General Public License.
```
I use the PKGBUILD at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zoem with only pkgver and hashsum adjusted .

How can I enable debugging symbols?

**Comment by goedel-gang** [comment]
Hi Stefan,

It seems zoem had a bug which the compilers started warning about in Arch,
leading to the AUR packager adding some compiler flags to override the warning.

I'm on Arch and everything seems to work fine when installing version 11.166 if
I patch in the bug fix - it's literally just changing `char` to `extern char` in
`version.h`. This should be fixed upstream in a zoem release soon, but in the
mean-time I added

```sh
prepare() {
  cd "$pkgname-${pkgver/./-}/src"
  sed -i '3s/^char/extern char/' "version.h"
}
```

to my PKGBUILD. I used the older PKGBUILD from the AUR, so my entire PKGBUILD
looks like this now:

```sh
# patched PKGBUILD from 62edb1e at https://aur.archlinux.org/zoem.git to fix bug in source code

# I'm not maintaining this and I take no responsibility for if it works or not

pkgname=zoem
pkgver=11.166
pkgrel=3
pkgdesc='Zoem programming language'
arch=('x86_64' 'i686')
url='http://micans.org/zoem/'
license=('GPL2')
source=("http://micans.org/zoem/src/$pkgname-${pkgver/./-}.tar.gz")
sha256sums=('1267a222ae2ee998a91dbe66df19cf998a0e7db45c7e59821049ae6b791f37fe')

prepare() {
  cd "$pkgname-${pkgver/./-}/src"
  sed -i '3s/^char/extern char/' "version.h"
}

build() {
  cd "$pkgname-${pkgver/./-}"
  ./configure --prefix=/usr
  make
}

package() {
  make -C "$pkgname-${pkgver/./-}" install DESTDIR="$pkgdir"
}

# vim:set ts=2 sw=2 et:
```

I'm not an ABS expert so maybe this isn't the perfect way to do it!

**Comment by stefanhusmann** [comment]
The prepare function also works for 21.341. No segfault anymore.

**Comment by micans** [comment]
Of old compilers used to be able to live with this lazy/erroneous declaration, but those days are gone apparently. The path from this issue to a segfault is intriguing; I assume that the line `export LDFLAGS="$LDFLAGS -Wl,--allow-multiple-definition"` in the `PKGBUILD` file was to combat compiler stringency (as it is a multiple definition issue).
Thanks for the bug report. I have some other changes coming up; there is a chance that a more recent version of zoem may get into some optional part of Debian. I've taken note of `zoem (null)` above, that's not as it should be either.
